KP : 1.0
KD : 0.0
ANGLE_LEVEL_1 : 10.0
SPEED_LEVEL_1 : 1.5
ANGLE_LEVEL_2 : 20.0
SPEED_LEVEL_2 : 1.0
SPEED_LEVEL_3 : 0.5


MIN_DISTANCE : 0.1
MAX_DISTANCE : 30.0
MIN_ANGLE : -45.0
MAX_ANGLE : 225.0
LOOKAHEAD_DISTANCE : 2.5
DESIRED_DISTANCE : 1.2
THETA : 45